sudo: required
services:
  - docker
before_install:
  - docker build -t nburny/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nburny/react-test npm test

after_success:
  - docker build -t nburny/multi-client ./client
  - docker build -t nburny/multi-nginx ./nginx
  - docker build -t nburny/multi-server ./server
  - docker build -t nburny/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nburny/multi-client
  - docker push nburny/multi-nginx
  - docker push nburny/multi-server
  - docker push nburny/multi-worker

language: generic
